config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :registered_applications

  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end

  get 'welcome/index'

  get 'welcome/about'

  root 'welcome#index'

end

app/models/application.rb
class Application < ActiveRecord::Base
  belongs_to :user

  validates :name, presence: true
  validates :url, presence: true
  validates :user, presence: true
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :registered_application

  validates :name, presence: true
  validates :registered_application, presence: true
end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base
  belongs_to :user
  has_many :events

  validates :name, presence: true
  validates :url, presence: true
  validates :user, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :registered_applications, dependent: :destroy

  before_save { self.email = email.downcase if email.present? }

  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 254 }

end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token

  before_filter :set_access_control_headers

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

  def create
    registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])

    if registered_application.nil?
      render json: {errors: "Unregistered application"}, status: :unprocessable_entity
    else
      @event = registered_application.events.new(event_params)
    end

    if @event && @event.save
      render json: @event, status: :created
    elsif @event
      render json: {errors: @event.errors}, status: :unprocessable_entity
    end
  end

  def preflight
    head 200
  end

  private

  def event_params
    params.require(:event).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @apps = RegisteredApplication.all
  end

  def new
    @app = RegisteredApplication.new
  end

  def create
    @app = RegisteredApplication.new
    @app.name = params[:registered_application][:name]
    @app.url = params[:registered_application][:url]
    @app.user = current_user

    if @app.save
      flash[:notice] = "Your application has been registered!"
      redirect_to @app
    else
      flash[:alert] = "There was an error registering your application. Please try again."
      render :new
    end
  end

  def edit
    @app = RegisteredApplication.find(params[:id])
  end

  def update
    @app = RegisteredApplication.find(params[:id])
    @app.name = params[:registered_application][:name]
    @app.url = params[:registered_application][:url]

    if @app.save
      flash[:notice] = "Your application has been updated."
      redirect_to @app
    else
      flash[:alert] = "There was an error updating your application. Please try again."
      render :edit
    end
  end

  def destroy
    @app = RegisteredApplication.find(params[:id])

    if @app.delete
      flash[:notice] = "Your application was successfully deleted"
      redirect_to registered_applications_path
    else
      flash[:alert] = "There was an error deleting your application. Please try again."
      redirect_to @app
    end
  end

  def show
    @app = RegisteredApplication.find(params[:id])
    @events = @app.events.group_by(&:name)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Metric</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="containter">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path, class: "nav-links" %></li>
      <li><%= link_to "About", welcome_about_path, class: "nav-links" %></li>
      <li><%= link_to "Apps", registered_applications_path, class: "nav-links" %></li>

      <div class="user-info">
        <% if user_signed_in? %>
          Signed in as: <strong><%= current_user.email %></strong> |
          <%= link_to 'Edit profile', edit_user_registration_path %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path %> -
          <%= link_to "Sign In", new_user_session_path %>
        <% end %>
      </div>
    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times</button>
    <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/registered_applications/create.html.erb
<h1>RegisteredApplications#create</h1>
<p>Find me in app/views/registered_applications/create.html.erb</p>

app/views/registered_applications/destroy.html.erb
<h1>RegisteredApplications#destroy</h1>
<p>Find me in app/views/registered_applications/destroy.html.erb</p>

app/views/registered_applications/edit.html.erb
<div class="container">
  <h1>Edit Application</h1>
  <div class="row">
    <div class="col-md-8">
      <%= form_for @app do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control', placeholder: "Enter App Name" %>
        </div>
        <div class="form-group">
          <%= f.label :url %>
          <%= f.text_field :url, class: 'form-control', placeholder: "Enter App URL" %>
        </div>
        <div class="form-group">
        <%= f.submit "Update App", class: 'btn btn-success' %>
        </div>
      <% end  %>
    </div>
  </div>
</div>

app/views/registered_applications/index.html.erb
<div class="container text-center">
  <div class="row">
  <h1>Apps</h1>
  <% if current_user %>
    <div>
      <%= link_to "Register a new app", new_registered_application_path, class: 'btn btn-success' %>
    </div>
  <% end %>
  <% @apps.each do |app| %>
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">
          <%= link_to app.name, app %>
        </h4>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/registered_applications/new.html.erb
<div class="container">
  <h1>Add a new Application</h1>
  <div class="row">
    <div class="col-md-8">
      <%= form_for @app do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control', placeholder: "Enter App Name" %>
        </div>
        <div class="form-group">
          <%= f.label :url %>
          <%= f.text_field :url, class: 'form-control', placeholder: "Enter App URL" %>
        </div>
        <div class="form-group">
        <%= f.submit "Register App", class: 'btn btn-success' %>
        </div>
      <% end  %>
    </div>
  </div>
</div>

app/views/registered_applications/show.html.erb
<div class="containter text-center">
  <h1><%= @app.name %></h1>
  <h4><%= @app.url %></h4>
    <%= link_to "Edit", edit_registered_application_path(@app), class: 'btn btn-success' %>
    <%= link_to "Delete", @app, method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure you want to delete this app?" } %>
</div>
<!-- <div class="row">
    <div class="col-md-8 col-md-offset-2 text-center">
      <table class="table table-hover">
        <tr>
          <th>Events</th>
          <th>Count</th>
        </tr>
        <% @events.each do |e| %>
        <tr>
          <th><%= e[0] %></th>
          <th><%= e[1].count %></th>
        </tr>
        <% end %>
      </table>
    </div>
  </div> -->
<%= pie_chart @app.events.group(:name).count %>

<%= line_chart @app.events.group_by_day(:created_at).count %>

app/views/registered_applications/update.html.erb
<h1>RegisteredApplications#update</h1>
<p>Find me in app/views/registered_applications/update.html.erb</p>

app/views/welcome/about.html.erb
<div class='text-center'>
  <h1>Follow me on Github!</h1>
  <a href="http://github.com/loganmartintran" class="btn btn-success">Let's Connect</a>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron text-center">
  <h1>Metric</h1>
  <p>
    <%= link_to "Sign In", new_user_session_path %>
    <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-success' %></p>
  </p>
</div>